// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_orfs_cpp
List find_orfs_cpp(CharacterVector seqs, CharacterVector start_codons, CharacterVector stop_codons, int min_body);
RcppExport SEXP _Ribostan_find_orfs_cpp(SEXP seqsSEXP, SEXP start_codonsSEXP, SEXP stop_codonsSEXP, SEXP min_bodySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type seqs(seqsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type start_codons(start_codonsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type stop_codons(stop_codonsSEXP);
    Rcpp::traits::input_parameter< int >::type min_body(min_bodySEXP);
    rcpp_result_gen = Rcpp::wrap(find_orfs_cpp(seqs, start_codons, stop_codons, min_body));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Ribostan_find_orfs_cpp", (DL_FUNC) &_Ribostan_find_orfs_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Ribostan(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
