# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find ORFs in a character vector of nucleotide sequences
#'
#' @param seqs Character vector of uppercase DNA sequences.
#' @param start_codon Length-1 character; start codon (default "ATG").
#' @param stop_codons Character vector; stop codons.
#' @param min_body Integer; minimum body length in nucleotides between the end
#'   of the start codon and the beginning of the stop codon.
#' @return A list with three integer vectors: \code{starts}, \code{ends}
#'   (1-based, inclusive), and \code{indices} (1-based index into \code{seqs}).
#' @keywords internal
find_orfs_cpp <- function(seqs, start_codon, stop_codons, min_body = 0L) {
    .Call('_Ribostan_find_orfs_cpp', PACKAGE = 'Ribostan', seqs, start_codon, stop_codons, min_body)
}

